# frozen_string_literal: true

require "huebrew/exporters/zsh_syntax_highlighting/v1"

RSpec.describe Huebrew::Exporters::ZshSyntaxHighlighting::V1 do
  let(:palette_path) { File.join(__dir__, "..", "..", "..", "data", "palettes", "radix_v3", "slate_light.yml") }
  let(:palette) { Huebrew::Palette.load_from_file(palette_path) }
  let(:exporter) { described_class.new }

  describe "#capabilities" do
    it "does not support alpha" do
      expect(exporter.capabilities[:supports_alpha]).to be false
    end

    it "requires alpha flattening" do
      expect(exporter.capabilities[:flatten_alpha]).to be true
    end

    it "does not want RGB format" do
      expect(exporter.capabilities[:wants_rgb]).to be false
    end
  end

  describe "#render" do
    it "renders ZSH Syntax Highlighting configuration" do
      result = exporter.render(palette: palette)

      expect(result).to be_a(String)
      expect(result).to include("ZSH_HIGHLIGHT_HIGHLIGHTERS=(main cursor)")
      expect(result).to include("typeset -gA ZSH_HIGHLIGHT_STYLES")
    end

    it "includes required ZSH_HIGHLIGHT_STYLES settings" do
      result = exporter.render(palette: palette)

      # Check for key style settings
      expect(result).to include("ZSH_HIGHLIGHT_STYLES[comment]=")
      expect(result).to include("ZSH_HIGHLIGHT_STYLES[alias]=")
      expect(result).to include("ZSH_HIGHLIGHT_STYLES[function]=")
      expect(result).to include("ZSH_HIGHLIGHT_STYLES[command]=")
      expect(result).to include("ZSH_HIGHLIGHT_STYLES[builtin]=")
      expect(result).to include("ZSH_HIGHLIGHT_STYLES[reserved-word]=")
      expect(result).to include("ZSH_HIGHLIGHT_STYLES[commandseparator]=")
      expect(result).to include("ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=")
      expect(result).to include("ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=")
      expect(result).to include("ZSH_HIGHLIGHT_STYLES[path]=")
      expect(result).to include("ZSH_HIGHLIGHT_STYLES[cursor]=")
    end

    it "uses hex color format" do
      result = exporter.render(palette: palette)

      # Should contain hex colors like #FCFCFD
      expect(result).to match(/#[0-9A-F]{6}/)
    end

    it "includes header comments" do
      result = exporter.render(palette: palette)

      expect(result).to include("# Generated by Huebrew")
      expect(result).to include("# Palette:")
      expect(result).to include("# Scheme:")
      expect(result).to include("before you activate zsh-syntax-highlighting")
    end

    it "maps colors correctly" do
      result = exporter.render(palette: palette)

      # Comment should use textMuted (step 11)
      expect(result).to include("ZSH_HIGHLIGHT_STYLES[comment]='fg=#60646C'")

      # Function/command should use solid (step 9)
      expect(result).to include("ZSH_HIGHLIGHT_STYLES[function]='fg=#8B8D98'")

      # Default should use text (step 12)
      expect(result).to include("ZSH_HIGHLIGHT_STYLES[default]='fg=#1C2024'")
    end

    it "sets cursor to standout" do
      result = exporter.render(palette: palette)

      expect(result).to include("ZSH_HIGHLIGHT_STYLES[cursor]='standout'")
    end

    it "raises error for unknown family" do
      expect {
        exporter.render(palette: palette, family: "unknown")
      }.to raise_error(Huebrew::ExportError)
    end
  end

  describe "#output_kind" do
    it "is string output" do
      expect(exporter.output_kind).to eq(:string)
    end
  end
end
