# frozen_string_literal: true

require_relative "../../exporter"

module Huebrew
  module Exporters
    module ZshSyntaxHighlighting
      # ZSH Syntax Highlighting exporter (v1)
      # Generates zsh-syntax-highlighting theme configuration
      class V1 < Exporter
        def initialize
          super
          @name = "ZSH Syntax Highlighting"
          @output_kind = :string
        end

        # ZSH doesn't support alpha
        def capabilities
          {
            supports_alpha: false,
            wants_rgb: false,
            flatten_alpha: true
          }
        end

        # Render ZSH Syntax Highlighting configuration
        # @param palette [Palette] Palette to export
        # @param family [String] Family name to export (defaults to first family)
        # @param dest [String, nil] Unused for string output
        # @return [String] ZSH Syntax Highlighting configuration
        def render(palette:, family: nil, dest: nil)
          family_name = family || palette.families.keys.first
          family_data = palette.families[family_name]

          raise ExportError, "Family '#{family_name}' not found" unless family_data

          # Get background color for alpha blending
          bg_color = family_data["steps"][1]

          # Build output
          output = []
          output << "# #{palette.name} (for zsh-syntax-highlighting)"
          output << "#"
          output << "# Generated by Huebrew"
          output << "# Palette: #{palette.name}"
          output << "# Scheme: #{palette.scheme}"
          output << "#"
          output << "# Paste this file's contents inside your ~/.zshrc before you activate zsh-syntax-highlighting"
          output << ""
          output << "ZSH_HIGHLIGHT_HIGHLIGHTERS=(main cursor)"
          output << "typeset -gA ZSH_HIGHLIGHT_STYLES"
          output << ""
          output << "# Main highlighter styling"
          output << ""

          # Map colors using the Radix taxonomy
          # Based on the Dracula example structure

          # Comments
          output << "## Comments"
          output << "ZSH_HIGHLIGHT_STYLES[comment]='fg=#{format_color(family_data["steps"][11], bg: bg_color)}'"
          output << ""

          # Functions/methods/commands
          output << "## Functions/methods"
          output << "ZSH_HIGHLIGHT_STYLES[alias]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[function]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[command]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[precommand]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=#{format_color(family_data["steps"][10], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#{format_color(family_data["steps"][10], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#{format_color(family_data["steps"][10], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << ""

          # Built-ins
          output << "## Built-ins"
          output << "ZSH_HIGHLIGHT_STYLES[builtin]='fg=#{format_color(family_data["steps"][10], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#{format_color(family_data["steps"][10], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#{format_color(family_data["steps"][10], bg: bg_color)}'"
          output << ""

          # Punctuation
          output << "## Punctuation"
          output << "ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=#{format_color(family_data["steps"][12], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-unquoted]='fg=#{format_color(family_data["steps"][12], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=#{format_color(family_data["steps"][12], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << ""

          # Strings
          output << "## Strings"
          output << "ZSH_HIGHLIGHT_STYLES[command-substitution-quoted]='fg=#{format_color(family_data["steps"][10], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-quoted]='fg=#{format_color(family_data["steps"][10], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#{format_color(family_data["steps"][10], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#{format_color(family_data["steps"][10], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[rc-quote]='fg=#{format_color(family_data["steps"][10], bg: bg_color)}'"
          output << ""

          # Variables
          output << "## Variables"
          output << "ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#{format_color(family_data["steps"][12], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#{format_color(family_data["steps"][12], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[assign]='fg=#{format_color(family_data["steps"][12], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[named-fd]='fg=#{format_color(family_data["steps"][12], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=#{format_color(family_data["steps"][12], bg: bg_color)}'"
          output << ""

          # Other
          output << "## Other"
          output << "ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[path]='fg=#{format_color(family_data["steps"][12], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#{format_color(family_data["steps"][12], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[globbing]='fg=#{format_color(family_data["steps"][12], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[back-quoted-argument-unclosed]='fg=#{format_color(family_data["steps"][9], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[redirection]='fg=#{format_color(family_data["steps"][12], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[arg0]='fg=#{format_color(family_data["steps"][12], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[default]='fg=#{format_color(family_data["steps"][12], bg: bg_color)}'"
          output << "ZSH_HIGHLIGHT_STYLES[cursor]='standout'"

          output.join("\n")
        end
      end
    end
  end
end
