# frozen_string_literal: true

require_relative "../../exporter"
require_relative "../../renderers/erb_renderer"

module Huebrew
  module Exporters
    module Tmux
      # Tmux color exporter (v1)
      # Generates tmux.conf color configuration
      class V1 < Exporter
        def initialize
          super
          @name = "Tmux"
          @output_kind = :file
        end

        # Tmux doesn't support alpha - must flatten
        def capabilities
          {
            supports_alpha: false,
            wants_rgb: false,
            flatten_alpha: true
          }
        end

        # Render tmux configuration
        # @param palette [Palette] Palette to export
        # @param family [String] Family name to export (defaults to first family)
        # @param dest [String, nil] Destination file path
        # @return [String] Path to output file
        def render(palette:, family: nil, dest: nil)
          family_name = family || palette.families.keys.first
          family_data = palette.families[family_name]

          raise ExportError, "Family '#{family_name}' not found" unless family_data

          # Get background color for alpha blending
          bg_color = family_data["steps"][1]

          # Map roles to colors
          colors = {}
          Palette::ROLE_STEP_MAP.each do |role, step|
            color = family_data["steps"][step]
            colors[role] = format_color(color, bg: bg_color) if color
          end

          # Find template
          template_path = Renderers::ErbRenderer.find_template("tmux.conf")
          unless template_path
            # Fallback to inline generation if no template
            return render_inline(palette, colors, dest)
          end

          # Render with template
          output = Renderers::ErbRenderer.render(template_path, {
            palette: palette,
            colors: colors
          })

          # Write to file
          output_path = dest || File.join(Dir.pwd, "tmux-#{palette.scheme}.conf")
          File.write(output_path, output)

          output_path
        end

        private

        def render_inline(palette, colors, dest)
          output = []
          output << "# Tmux color configuration"
          output << "# Generated by Huebrew"
          output << "# Palette: #{palette.name}"
          output << "# Scheme: #{palette.scheme}"
          output << ""
          output << "# Status bar"
          output << "set -g status-style \"bg=#{colors["bgSubtle"]},fg=#{colors["text"]}\""
          output << "set -g status-left-style \"bg=#{colors["solid"]},fg=#{colors["bg"]}\""
          output << "set -g status-right-style \"bg=#{colors["bgSubtle"]},fg=#{colors["textMuted"]}\""
          output << ""
          output << "# Window status"
          output << "setw -g window-status-style \"bg=#{colors["bgSubtle"]},fg=#{colors["textMuted"]}\""
          output << "setw -g window-status-current-style \"bg=#{colors["surface"]},fg=#{colors["text"]}\""
          output << ""
          output << "# Pane borders"
          output << "set -g pane-border-style \"fg=#{colors["border"]}\""
          output << "set -g pane-active-border-style \"fg=#{colors["solid"]}\""

          output_path = dest || File.join(Dir.pwd, "tmux-#{palette.scheme}.conf")
          File.write(output_path, output.join("\n"))

          output_path
        end
      end
    end
  end
end
